# Generated by Django 5.1.3 on 2026-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ENDED', 'ENDED')], default='NOT_STARTED', max_length=20, verbose_name='Event Status'),
        ),
    ]
